name: price_tag_app
description: Price tag generator app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pdf: ^3.10.8
  printing: ^5.11.0

flutter:
  uses-material-design: true
  
